user_created_success = 'User Created Successfully'
user_login_success = 'User Logged-In Successfully'
user_data_fetch_success = 'User Data Fetched Successfully'
user_logout_success = 'User Logged-Out Successfully'
server_error_message = 'OOPS! Something Went Wrong'
wrong_url_message = 'Invalid Api Call'
data_already_exist_message = 'The Given Data Already Exist'
invalid_data_string = 'Invalid Data'
user_not_found = 'The Given Email Not Found'
invalid_credentials = 'Invalid Credentials'
refresh_token_success = 'Refresh Token Generated'
duplicate_provider_message = 'Provider Data Duplicated'
product_created_response = 'Product Created Successfully'
product_deleted_response = 'Product Deleted Successfully'
product_updated_success = 'Product Updated Successfully'
location_created_response = 'Warehouse Creatd Successfully'
location_not_found = 'The Given Location Not Found'
location_updated_sender = 'Location Updated Successfully'
success_response = 'Data Fetched'


